// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQvrpeQIJbU-DVG-Wv1KcKVRCv_gt-hU',
    appId: '1:317381738249:web:126fbd969f0f96d6bd1dd8',
    messagingSenderId: '317381738249',
    projectId: 'elfouad-coffee-beans-b1fc2',
    authDomain: 'elfouad-coffee-beans-b1fc2.firebaseapp.com',
    storageBucket: 'elfouad-coffee-beans-b1fc2.firebasestorage.app',
    measurementId: 'G-261ZYFWZRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdpWB7hpZWGBANxnhHNl9vDAKG6XRttpQ',
    appId: '1:317381738249:android:505e9339286b629fbd1dd8',
    messagingSenderId: '317381738249',
    projectId: 'elfouad-coffee-beans-b1fc2',
    storageBucket: 'elfouad-coffee-beans-b1fc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BV73Ty6XJWTE3XakFRVDlMucWez7DGI',
    appId: '1:317381738249:ios:7a65bf98237d656fbd1dd8',
    messagingSenderId: '317381738249',
    projectId: 'elfouad-coffee-beans-b1fc2',
    storageBucket: 'elfouad-coffee-beans-b1fc2.firebasestorage.app',
    iosBundleId: 'com.example.elfouadCoffeeBeans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BV73Ty6XJWTE3XakFRVDlMucWez7DGI',
    appId: '1:317381738249:ios:7a65bf98237d656fbd1dd8',
    messagingSenderId: '317381738249',
    projectId: 'elfouad-coffee-beans-b1fc2',
    storageBucket: 'elfouad-coffee-beans-b1fc2.firebasestorage.app',
    iosBundleId: 'com.example.elfouadCoffeeBeans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNQvrpeQIJbU-DVG-Wv1KcKVRCv_gt-hU',
    appId: '1:317381738249:web:a57e92b00b40d0f1bd1dd8',
    messagingSenderId: '317381738249',
    projectId: 'elfouad-coffee-beans-b1fc2',
    authDomain: 'elfouad-coffee-beans-b1fc2.firebaseapp.com',
    storageBucket: 'elfouad-coffee-beans-b1fc2.firebasestorage.app',
    measurementId: 'G-F03PHVLRQL',
  );
}
